services:
  - type: web
    name: crud-usuarios-api
    runtime: node
    buildCommand: npm install
    startCommand: npm run server:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
