services:
  - type: web
    name: crud-usuarios-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm run server:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
